services:
  - type: web
    name: de-role-evolution-dashboard
    env: python

    buildCommand: pip install -r requirements.txt

    startCommand: streamlit run streamlit_app/app.py --server.port=$PORT --server.address=0.0.0.0